name: Flutter web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build/web/
    - uses: actions/download-artifact@v1
      with:
        name: build
    - run: git checkout --orphan github-page
    - run: git add build/web .
    - run: git commit -m "new build"
